#!/bin/bash
scrot /tmp/screen.png
convert /tmp/screen.png -scale 10% -scale 1000% /tmp/screen.png
[[ -f /home/jbanier/Pictures/icons/lock-icon.png ]] && convert /tmp/screen.png /usr/share/transmission/web/style/transmission/images/lock_icon.png -gravity center -composite -matte /tmp/screen.png
i3lock -u -i /tmp/screen.png
